TARGET = circle celsius2Fahr fahr2Celsius fahr2Celsius2 fahr2Celsius3 limits literal score triangle

all: ${TARGET}

circle: $@
celsius2Fahr: $@
fahr2Celsius: $@
fahr2Celsius2: $@
fahr2Celsius3: $@
limits: $@
literal: $@
score: $@
triangle: $@

celsius2Fahr: $@
clean:
	rm -f ${TARGET}circle celsius2Fahr
